### PR TITLE
Code organization and Cocoa conventions

### PR DESCRIPTION
**Pull request by interstateone**
Sorry in advance, the diffs for this PR are pretty involved and I understand if you don't want to merge it. :smile:

What this changes:
- Extracts VM manipulation code into a VMManager class
- Specifies all app-specific filesystem paths in a NSURL category
- Adds support for localization of all user-facing strings
- Some code style and variable name changes for consistency and Cocoa conventions

Why:

I think this is a step towards making it easier to test the little bit of logic that is handled in the Objective-C part of the app, and adopts some Cocoa conventions. These changes could also be applied to some of the other similar projects you have.

Thanks for making this project! I really appreciate how easy it makes it to get Kubernetes running locally on a Mac.

### CODE REVIEW

**Comment by rimusz** [comment]
oh my ..., big refactoring is done there :)
I do not want to merge to the master yet, as I have travel a lot for the next few weeks, so do not want to break the App which I want to use for demos :) But would be nice to get merged at some point next month and reuse for my other Apps too :)

Noticed a few errors in 
screenshot 2015-10-30 08 47 41

**Comment by rimusz** [comment]
also, are you good in converting to swift? that help also would be good :)

**Comment by interstateone** [comment]
Sounds good, I'll wait to hear back about any merge issues when you're ready. Regarding the errors you shared: are you seeing those on the head of this branch? Those should have been fixed.

Swift: yes :smile: Can do that as a separate PR once this one is merged.

**Comment by rimusz** [comment]
I tried to compile your repo master brach and got that error.
Awesome regarding the Swift :)
I have two Apps based on xhyve, both I would love to both to get refactored :) and convert them to Swift later. Then I can take one as a base and move my other Apps to xhyve & Swift :)

**Comment by interstateone** [comment]
This PR is from my CodeOrganization branch to your master, my master hasn't been changed.

**Comment by rimusz** [comment]
phew, finished with my conferences
I have made some good improvements to the App, can you please rebase your changes against the latest master branch.

**Comment by interstateone** [comment]
@rimusz I've rebased this onto your latest master and fixed the few conflicts there were.

**Comment by rimusz** [comment]
awesome job, thanks man
I will merge it, then I need to do some refactoring of shells scripts :)

Would you mind to do the same refactoring for my other xhyve based App https://github.com/TheNewNormal/coreos-osx please.

Then we can move on to swift.
When we have kube-solo ported to swift I can start working on https://github.com/TheNewNormal/kube-cluster-osx, xhyve based k8s cluster with master+ 2 nodes

**Comment by interstateone** [comment]
Not sure I'll have time to refactor the other repo for a while, going to be taking an extended trip without much internet, which I need to prepare for. Hope I was able to help while I could :) All the best.

**Comment by rimusz** [comment]
@interstateone sure, not a big deal, you already have done an outstanding job :)
I will use as a base kube-solo App for my future Apps, and will try to find some time to convert the coreos-osx one myself.

**Pull request merged**
