### PR TITLE
Added missing stop() method for "ksolo stop" command

### PR DESCRIPTION
**Pull request by IanGSY**

### CODE REVIEW

**Comment by rimusz** [comment]
thanks for spoting it, and for the PR, will cut a new release tomorrow

**Comment by IanGSY** [comment]
Thanks for accepting + merging.

**Comment by rimusz** [comment]
thanks for the PR 👍 
btw is the latest app version working fine for, specially VM's UP, as there is issue opened #151 whcih I cannot reproduce

**Comment by IanGSY** [comment]
I am not sure about #151 but I used to experience a bug where I was unable to re-connect to the cluster after letting my mac go to sleep. This is now working.

**Comment by rimusz** [comment]
sleep I know was the issue before for sure. @AntonioMeireles can you confirm/explain about sleep?

**Pull request merged**
