### PR TITLE
Open user's preferred shell if defined, otherwise bash

### PR DESCRIPTION
**Pull request by tpbrown**
Nothing fancy.  Just making it so that [fish](http://fishshell.com) junkies are happy ;-)

### CODE REVIEW

**Comment by AntonioMeireles** [comment]
LGTM

**Comment by tpbrown** [comment]
dammmmn you're fast!

**Comment by rimusz** [comment]
@Tpbrown could you please update `first-init.command` and `up.command` as well?
and test that the change works everywhere as I do not use `fish` stuff myself :)

**Comment by tpbrown** [comment]
@rimusz done.    I don't have XCode installed so I tested by copying the modified commands into Kube-Solo.app/Contents/Resources and re-ran setup, ran through up, and OS shell.

**Comment by rimusz** [comment]
Closing this one, as it was conflicting with my changes, but I have cherry picked your changes and implemented. Thanks for it :)

**Pull request closed without merging**
