### PR TITLE
[WIP] Adding the capability to use a local kubernetes.tar.gz for updates

### PR DESCRIPTION
**Pull request by chrislovecnm**
So I have added the capability to use a local install.  Got a small bug could use an assistance with.

For some reason using a `~/kubernetes.tar.gz` with a `~/` path is not working.  Using `/User/myusername/kubernetes.tar.gz` works fine.  Any ideas?

### CODE REVIEW

**Comment by rimusz** [comment]
@chrislovecnm use `$HOME/` instead of `~/`
What about the placing the file to `~/kube-solo/tmp/kubernetes.tar.gz` and install from there?

**Comment by chrislovecnm** [comment]
I did both in the code 😄

**Comment by chrislovecnm** [comment]
@rimusz does this meet your needs?  Works great for me

**Comment by rimusz** [comment]
@chrislovecnm I have changed that you have to copy the file to `~/kube-solo/tmp` and it will be installed from there, no option to type the file's path

**Pull request merged**
