### PR TITLE
Refactor: Change loud to normal notifications, see #155

### PR DESCRIPTION
**Pull request by franz-josef-kaiser**
Remove multiple exclamation marks.
Exchange multiple periods with a horizontal ellipsis.
Exchange _macOS_ with the correct _OS X_ name of the OS.

### CODE REVIEW

**Comment by rimusz** [comment]
thanks for PR. could you please remove macOS changes to OS X, as it is now called macOS

**Comment by franz-josef-kaiser** [comment]
@rimusz I did not know that. Thanks for the heads up! Will change.

**Comment by franz-josef-kaiser** [comment]
@rimusz Renamed, rebased and squashed into a single commit. Looks good to you?

**Comment by rimusz** [comment]
cool thanks, will review and merge later one, doing house duties right now :)

**Comment by rimusz** [comment]
thanks, all good, I have merged it :)

**Pull request merged**
